CREATE TABLE OPH$OBJ
(
   ID                  NUMBER (38) CONSTRAINT OPH$OBJ_ID_NN NOT NULL,
   TYPE_ID             NUMBER (38) CONSTRAINT OPH$OBJ_OPH$TYPE_ID_NN NOT NULL,
   OWNER               VARCHAR2 (30 CHAR) CONSTRAINT OPH$OBJ_OWNER_NN NOT NULL,
   NAME                VARCHAR2 (30 CHAR) CONSTRAINT OPH$OBJ_NAME_NN NOT NULL,
   ENABLED             NUMBER (1) DEFAULT 0 CONSTRAINT OPH$OBJ_ENABLED_NN NOT NULL,
   ORDER#              NUMBER (19),
   LAST_RUN_START_TS   TIMESTAMP (6) WITH LOCAL TIME ZONE,
   LAST_RUN_END_TS     TIMESTAMP (6) WITH LOCAL TIME ZONE,
   last_run_duration   INTERVAL DAY TO SECOND
                          GENERATED ALWAYS AS (last_run_end_ts - last_run_start_ts)
)
TABLESPACE &DATA_TBS.;

COMMENT ON TABLE OPH$OBJ IS 'Partitioned object';

COMMENT ON COLUMN OPH$OBJ.ID IS 'Technical unique identifier';

COMMENT ON COLUMN OPH$OBJ.TYPE_ID IS 'Reference to OPH$OTYPE.';

COMMENT ON COLUMN OPH$OBJ.OWNER IS 'Name of the object owner';

COMMENT ON COLUMN OPH$OBJ.NAME IS 'Name of the object';

COMMENT ON COLUMN OPH$OBJ.ENABLED IS 'Partition handling enabled';

COMMENT ON COLUMN OPH$OBJ.ORDER# IS
   'Order number in which the objects will be handled';

CREATE SEQUENCE OPH$OBJ_ID_SEQ START WITH 1000 INCREMENT BY 1 NOCACHE ORDER;

CREATE UNIQUE INDEX OPH$OBJ_ID_UX
   ON OPH$OBJ (ID)
   TABLESPACE &INDEX_TBS.;


CREATE UNIQUE INDEX OPH$OBJ_TYPE_ID_OWNER_NAME_UX
   ON OPH$OBJ (TYPE_ID, OWNER, NAME)
   TABLESPACE &INDEX_TBS.;

ALTER TABLE OPH$OBJ ADD
  CONSTRAINT OPH$OBJ_ENABLED_CK
  CHECK (enabled IN (0, 1))
  ENABLE VALIDATE;

ALTER TABLE OPH$OBJ ADD   CONSTRAINT OPH$OBJ_PK
  PRIMARY KEY
  (ID)
  ENABLE VALIDATE;

ALTER TABLE OPH$OBJ ADD  CONSTRAINT OPH$OBJ_TYPE_ID_OWNER_NAME_UK
  UNIQUE (TYPE_ID, OWNER, NAME)
  ENABLE VALIDATE;

ALTER TABLE OPH$OBJ ADD (
  CONSTRAINT OPH$OBJ_OPH$OBJ_TYPE_FK
  FOREIGN KEY (TYPE_ID)
  REFERENCES OPH$OBJ_TYPE (ID)
  ENABLE VALIDATE);