CREATE TABLE OPH$KEY
(
   OBJ_ID        NUMBER (38) CONSTRAINT OPH$KEY_OPH$OBJ_ID_NN NOT NULL,
   TYPE_ID       NUMBER (38) CONSTRAINT OPH$KEY_OPH$TYPE_ID_NN NOT NULL,
   TECH_ID       NUMBER (38) CONSTRAINT OPH$KEY_OPH$TECH_ID_NN NOT NULL,
   COLUMN_NAME   VARCHAR2 (30 CHAR)
                    CONSTRAINT OPH$KEY_COLUMN_NAME_NN NOT NULL,
   ENABLED       NUMBER (1) DEFAULT 0 CONSTRAINT OPH$KEY_ENABLED_NN NOT NULL
)
TABLESPACE &DATA_TBS.;

COMMENT ON TABLE OPH$KEY IS 'Partition key definition';

COMMENT ON COLUMN OPH$KEY.OBJ_ID IS 'Object the partition key belongs to';

COMMENT ON COLUMN OPH$KEY.TYPE_ID IS 'Partition type.';

COMMENT ON COLUMN OPH$KEY.TECH_ID IS
   'Partition technique used for this partition key';

COMMENT ON COLUMN OPH$KEY.COLUMN_NAME IS
   'Column name which is the partition key';

COMMENT ON COLUMN OPH$KEY.ENABLED IS
   'Is this column handled by Partitionhandler';

CREATE INDEX OPH$KEY_ENABLED_IX
   ON OPH$KEY (ENABLED)
   TABLESPACE &INDEX_TBS.;

CREATE UNIQUE INDEX OPH$KEY_OBJ_ID_COLUMN_NAME_UX
   ON OPH$KEY (OBJ_ID, COLUMN_NAME)
   TABLESPACE &INDEX_TBS.;


CREATE UNIQUE INDEX OPH$KEY_OBJ_ID_TYPE_ID_UX
   ON OPH$KEY (OBJ_ID, TYPE_ID)
   TABLESPACE &INDEX_TBS.;


ALTER TABLE OPH$KEY ADD
  CONSTRAINT OPH$KEY_ENABLED_CK
  CHECK (enabled IN (0, 1))
  ENABLE VALIDATE;
ALTER TABLE OPH$KEY ADD  CONSTRAINT OPH$KEY_PK
  PRIMARY KEY
  (OBJ_ID, TYPE_ID)
  USING INDEX OPH$KEY_OBJ_ID_TYPE_ID_UX
  ENABLE VALIDATE;
ALTER TABLE OPH$KEY ADD  CONSTRAINT OPH$KEY_OBJ_ID_COLUMN_NAME_UK
  UNIQUE (OBJ_ID, COLUMN_NAME)
  USING INDEX OPH$KEY_OBJ_ID_COLUMN_NAME_UX
  ENABLE VALIDATE;


ALTER TABLE OPH$KEY ADD  CONSTRAINT OPH$KEY_OPH$OBJ_FK
  FOREIGN KEY (OBJ_ID)
  REFERENCES OPH$OBJ (ID)
  ON DELETE CASCADE
  ENABLE VALIDATE;
ALTER TABLE OPH$KEY ADD  CONSTRAINT OPH$KEY_OPH$KEY_TYPE_FK
  FOREIGN KEY (TYPE_ID)
  REFERENCES OPH$KEY_TYPE (ID)
  ENABLE VALIDATE;
ALTER TABLE OPH$KEY ADD  CONSTRAINT OPH$KEY_OPH$TECH_FK
  FOREIGN KEY (TECH_ID)
  REFERENCES OPH$TECH (ID)
  ENABLE VALIDATE;

CREATE SEQUENCE OPH$KEY_ID_SEQ START WITH 1000 INCREMENT BY 1 NOCACHE ORDER;
